#!/usr/bin/env python3
"""
Automated C++14 Solution Verifier & Trace Table Generator
Part of the Akashic Record Competitive Programming Offline Library pipeline.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path


def to_typst_literal(val):
    """Convert a Python object to its Typst syntax representation."""
    if val is None:
        return "none"
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, str):
        return json.dumps(val, ensure_ascii=False)
    if isinstance(val, list):
        if len(val) == 0:
            return "()"
        if len(val) == 1:
            return f"({to_typst_literal(val[0])}, )"
        return f"({', '.join(to_typst_literal(item) for item in val)})"
    if isinstance(val, dict):
        if len(val) == 0:
            return "(:)"
        entries = [f'"{k}": {to_typst_literal(v)}' for k, v in val.items()]
        return f"({', '.join(entries)})"
    return json.dumps(str(val), ensure_ascii=False)


def generate_typst_content(test_results):
    """Generate a complete, valid Typst file with #trace-table definitions and calls."""
    lines = [
        "// Execution Trace Table - Auto-generated by tools/verifier/run_verifier.py",
        "// Akashic Record - Competitive Programming C++14 Offline Library",
        "",
        "#let format-val(v) = { if type(v) == str { v } else { repr(v) } }",
        "",
        "#let trace-table(",
        "  test-id: none,",
        '  status: "AC",',
        "  traces: (),",
        ") = {",
        "  let rows = ()",
        "  for t in traces {",
        '    if t.at("type", default: "") == "step" {',
        '      rows.push((format-val(t.at("step", default: "-")), t.at("msg", default: ""), "-"))',
        '    } else if t.at("type", default: "") == "var" {',
        '      rows.push(("-", t.at("name", default: ""), format-val(t.at("val", default: ""))))',
        '    } else if t.at("type", default: "") == "array" {',
        '      rows.push(("-", t.at("name", default: ""), format-val(t.at("values", default: ()))))',
        "    }",
        "  }",
        "  table(",
        "    columns: (1.8cm, 2.5fr, 2.5fr),",
        "    align: (center, left, left),",
        "    stroke: 0.5pt + luma(120),",
        "    table.header([*Bước*], [*Mô tả / Biến*], [*Giá trị*]),",
        "    ..rows.flatten().map(x => [#x])",
        "  )",
        "}",
        "",
    ]

    for item in test_results:
        t_id = item.get("id")
        status = item.get("status", "UNKNOWN")
        traces = item.get("traces", [])
        lines.append(f"// --- Test Case {t_id} [{status}] ---")
        lines.append("#trace-table(")
        lines.append(f"  test-id: {to_typst_literal(t_id)},")
        lines.append(f"  status: {to_typst_literal(status)},")
        lines.append(f"  traces: {to_typst_literal(traces)},")
        lines.append(")")
        lines.append("")

    return "\n".join(lines)


def compile_solution(src_path, bin_path, compiler="g++", cxx_std="c++14"):
    """Compile C++ solution with -std=c++14 -O2 -Wall -DENABLE_TRACE."""
    verifier_dir = Path(__file__).resolve().parent
    cmd = [
        compiler,
        f"-std={cxx_std}",
        "-O2",
        "-Wall",
        "-DENABLE_TRACE",
        f"-I{verifier_dir}",
        f"-I{src_path.parent}",
        str(src_path),
        "-o",
        str(bin_path),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    return res


def parse_trace_lines(stderr_str):
    """Extract and parse [TRACE_JSON]: JSON objects from stderr."""
    traces = []
    prefix = "[TRACE_JSON]: "
    for line in stderr_str.splitlines():
        idx = line.find(prefix)
        if idx != -1:
            json_str = line[idx + len(prefix):].strip()
            try:
                obj = json.loads(json_str)
                traces.append(obj)
            except json.JSONDecodeError:
                pass
    return traces


def unescape_string(text):
    """Convert literal escape sequences like \\n or \\r\\n to real newlines."""
    if not isinstance(text, str):
        return text
    if "\\r\\n" in text or "\\n" in text or "\\t" in text:
        text = text.replace("\\r\\n", "\n").replace("\\n", "\n").replace("\\t", "\t")
    return text


def normalize_output(text):
    """Normalize output by stripping each line and trailing whitespace."""
    if text is None:
        return ""
    lines = [line.strip() for line in text.strip().splitlines()]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Verify C++14 solutions against test suites and generate trace tables."
    )
    parser.add_argument("--src", required=True, type=Path, help="Path to C++ source file")
    parser.add_argument("--tests", required=True, type=Path, help="Path to tests JSON file")
    parser.add_argument("--out-typst", required=True, type=Path, help="Path to output Typst file")
    parser.add_argument("--out-web", required=True, type=Path, help="Path to output Web JSON file")
    parser.add_argument("--compiler", default="g++", help="C++ compiler executable (default: g++)")
    parser.add_argument("--cxx-std", default="c++14", help="C++ standard (default: c++14)")
    parser.add_argument("--timeout", type=float, default=5.0, help="Per-test timeout in seconds")

    args = parser.parse_args()

    src_path = args.src.resolve()
    if not src_path.is_file():
        sys.stderr.write(f"Error: Source file not found: {src_path}\n")
        sys.exit(1)

    tests_path = args.tests.resolve()
    if not tests_path.is_file():
        sys.stderr.write(f"Error: Tests file not found: {tests_path}\n")
        sys.exit(1)

    try:
        with open(tests_path, "r", encoding="utf-8") as f:
            tests_raw = json.load(f)
    except Exception as e:
        sys.stderr.write(f"Error reading tests JSON: {e}\n")
        sys.exit(1)

    if isinstance(tests_raw, list):
        tests_data = tests_raw
    elif isinstance(tests_raw, dict) and "tests" in tests_raw:
        tests_data = tests_raw["tests"]
    else:
        sys.stderr.write("Error: Tests JSON must be a list or dict with 'tests' key\n")
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp_dir:
        bin_path = Path(tmp_dir) / "solution_bin"
        compile_res = compile_solution(
            src_path, bin_path, compiler=args.compiler, cxx_std=args.cxx_std
        )
        if compile_res.returncode != 0:
            sys.stderr.write(f"Compilation failed:\n{compile_res.stderr}\n")
            # Write empty/error web output and typst before exiting
            args.out_web.parent.mkdir(parents=True, exist_ok=True)
            args.out_typst.parent.mkdir(parents=True, exist_ok=True)
            with open(args.out_web, "w", encoding="utf-8") as f:
                json.dump([], f, indent=2)
            with open(args.out_typst, "w", encoding="utf-8") as f:
                f.write("// Compilation failed\n")
            sys.exit(1)

        results = []
        all_passed = True

        for idx, test_entry in enumerate(tests_data):
            test_id = test_entry.get("id", idx + 1)
            raw_input = test_entry.get("input", "")
            raw_expected = test_entry.get("expected", "")
            test_input = unescape_string(raw_input)
            expected_output = unescape_string(raw_expected)

            start_t = time.perf_counter()
            try:
                proc = subprocess.run(
                    [str(bin_path)],
                    input=test_input,
                    capture_output=True,
                    text=True,
                    timeout=args.timeout,
                )
                elapsed_ms = round((time.perf_counter() - start_t) * 1000, 2)
                stdout = proc.stdout
                stderr = proc.stderr

                traces = parse_trace_lines(stderr)

                if proc.returncode != 0:
                    status = "RTE"
                    all_passed = False
                else:
                    norm_actual = normalize_output(stdout)
                    norm_expected = normalize_output(expected_output)
                    if norm_actual == norm_expected:
                        status = "AC"
                    else:
                        status = "WA"
                        all_passed = False

            except subprocess.TimeoutExpired:
                elapsed_ms = round(args.timeout * 1000, 2)
                stdout = ""
                stderr = ""
                traces = []
                status = "TLE"
                all_passed = False

            results.append({
                "id": test_id,
                "input": test_input,
                "expected": expected_output,
                "actual": stdout,
                "status": status,
                "execution_time_ms": elapsed_ms,
                "traces": traces,
            })

        # Ensure parent directories exist
        args.out_web.parent.mkdir(parents=True, exist_ok=True)
        args.out_typst.parent.mkdir(parents=True, exist_ok=True)

        with open(args.out_web, "w", encoding="utf-8") as f:
            json.dump(results, f, ensure_ascii=False, indent=2)

        typst_content = generate_typst_content(results)
        with open(args.out_typst, "w", encoding="utf-8") as f:
            f.write(typst_content)

        # Print summary
        passed_count = sum(1 for r in results if r["status"] == "AC")
        print(f"Verifier results: {passed_count}/{len(results)} tests passed.")

        if not all_passed:
            sys.exit(1)
        sys.exit(0)


if __name__ == "__main__":
    main()
